from .EasyTargetSettingViewClass import EasyTargetSettingView as EasyTargetSettingView
from .EasyDeleteStringViewClass import EasyDeleteStringView as EasyDeleteStringView
from .EasyMLCompleteViewClass import EasyMLCompleteView as EasyMLCompleteView
from .EasyPredictViewClass import EasyPredictView as EasyPredictView
from .EasyUploadViewClass import EasyUploadView as EasyUploadView
