# Generated by Django 3.2.3 on 2022-02-12 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    sql = """
    CREATE VIEW models_by_user AS 
    SELECT models.id as id, models.path as model_path, model_types.type as model_type, original_data.file_name as file_name,users.id as user_id , users.username as user_name, ensemble_compositions.ensemble_evaluation_id as ensemble_id
    FROM models
    LEFT OUTER JOIN machine_learning
    ON models.machine_learning_id = machine_learning.id
    LEFT OUTER JOIN feature_values
    ON machine_learning.feature_value_id = feature_values.id
    LEFT OUTER JOIN original_data
    ON feature_values.original_data_id = original_data.id
    LEFT OUTER JOIN users
    ON original_data.user_id = users.id
    LEFT OUTER JOIN model_types
    ON feature_values.model_type_id = model_types.id
    LEFT OUTER JOIN ensemble_compositions
    ON models.id = ensemble_compositions.model_id;
    """

    reverse_sql = """
    DROP VIEW models_by_user;
    """

    operations = [
        migrations.RunSQL(sql, reverse_sql),
    ]
