# Generated by Django 3.2.3 on 2022-02-12 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyai', '0001_initial'),
    ]

    sql = """
CREATE VIEW learn_plan AS 
SELECT models.id as id, feature_values.objective as objective, tasks.task_name as task
FROM models
LEFT OUTER JOIN machine_learning
ON models.machine_learning_id = machine_learning.id
LEFT OUTER JOIN feature_values
ON machine_learning.feature_value_id = feature_values.id
LEFT OUTER JOIN tasks
ON feature_values.task_id = tasks.id;

    """

    reverse_sql = """
    DROP VIEW learn_plan;
    """

    operations = [
        migrations.RunSQL(sql, reverse_sql),
    ]
