# Generated by Django 3.2.3 on 2022-02-12 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyai', '0001_initial'),
    ]

    sql = """
CREATE VIEW done_delete_string AS
SELECT models.id as model_id, delete_string.delete_column
FROM models
LEFT OUTER JOIN machine_learning
ON models.machine_learning_id = machine_learning.id
LEFT OUTER JOIN feature_values
ON machine_learning.feature_value_id = feature_values.id
LEFT OUTER JOIN delete_string
ON feature_values.id = delete_string.feature_value_id;
    """

    reverse_sql = """
    DROP VIEW done_delete_string;
    """

    operations = [
        migrations.RunSQL(sql, reverse_sql),
    ]
