# Generated by Django 3.2.3 on 2022-02-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyai', '0001_initial'),
    ]

    sql = """
CREATE VIEW done_replace_string AS
SELECT models.id as model_id, replace_string.column_name, replace_string.replace_before as before_str, replace_string.replace_after as after_str
FROM models
LEFT OUTER JOIN machine_learning
ON models.machine_learning_id = machine_learning.id
LEFT OUTER JOIN feature_values
ON machine_learning.feature_value_id = feature_values.id
LEFT OUTER JOIN replace_string
ON feature_values.id = replace_string.feature_value_id;
"""

    reverse_sql = """
    DROP VIEW done_replace_string;
    """

    operations = [
        migrations.RunSQL(sql, reverse_sql),
    ]
