# Generated by Django 3.2.3 on 2022-02-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyai', '0001_initial'),
    ]

    sql = """
CREATE VIEW done_missing AS
SELECT models.id as model_id, missing_processing.column_name, missing_processing.replace_str as fill_str
FROM models
LEFT OUTER JOIN machine_learning
ON models.machine_learning_id = machine_learning.id
LEFT OUTER JOIN feature_values
ON machine_learning.feature_value_id = feature_values.id
LEFT OUTER JOIN missing_processing
ON feature_values.id = missing_processing.feature_value_id;
"""

    reverse_sql = """
    DROP VIEW done_missing;
    """

    operations = [
        migrations.RunSQL(sql, reverse_sql),
    ]
