# Generated by Django 3.2.3 on 2022-02-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyai', '0001_initial'),
        ]

    sql = """
CREATE VIEW model_info AS
SELECT models.id as model_id, model_types.type as model_type, ensemble_compositions.ensemble_evaluation_id as ensemble_id, original_data.path as original_path, users.id as user_id
FROM models
LEFT OUTER JOIN machine_learning
ON models.machine_learning_id = machine_learning.id
LEFT OUTER JOIN feature_values
ON machine_learning.feature_value_id = feature_values.id
LEFT OUTER JOIN model_types
ON feature_values.model_type_id = model_types.id
LEFT OUTER JOIN ensemble_compositions
ON models.id = ensemble_compositions.model_id
LEFT OUTER JOIN original_data
ON feature_values.original_data_id = original_data.id
LEFT OUTER JOIN users
ON original_data.user_id = users.id;
"""

    reverse_sql = """
    DROP VIEW model_info;
    """

    operations = [
        migrations.RunSQL(sql, reverse_sql),
    ]
