# Generated by Django 3.2.3 on 2022-02-12 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyai', '0002'),
        ('easyai', '0003'),
        ('easyai', '0004'),
        ('easyai', '0005'),
        ('easyai', '0006'),
        ('easyai', '0007'),
    ]

    operations = [
    ]
